theme = "catppuccin_mocha"

[editor]

# basically theming
true-color = true
undercurl = true
bufferline = "multiple"
color-modes = true

statusline.mode.normal = "normal"
statusline.mode.insert = "insert"
statusline.mode.select = "select"
statusline.separator = "/"
statusline.left = ["mode", "spacer", "file-name", "position", "separator", "total-line-numbers", "spacer", "file-modification-indicator", "read-only-indicator"]
statusline.right = ["spinner", "spacer", "diagnostics", "spacer", "version-control", "spacer", "primary-selection-length", "separator", "selections", "register"]
cursorline = true
gutters.layout = ["diff", "spacer"]
preview-completion-insert = false
scrolloff = 10
scroll-lines = 1
soft-wrap.enable = true

# behaviors
shell = ["fish", "-c"]
lsp.display-messages = true
auto-format = false
file-picker.hidden = false
file-picker.ignore = false
file-picker.git-ignore = true

# diagnostics
end-of-line-diagnostics = "info"
inline-diagnostics.cursor-line = "info"

[keys]

normal.esc = [ "collapse_selection", "keep_primary_selection" ]

normal.i = [ "collapse_selection", "insert_mode" ]
select.i = [ "collapse_selection", "insert_mode" ]
normal.a = [ "collapse_selection", "append_mode" ]
select.a = [ "collapse_selection", "append_mode" ]
normal.X = "extend_line_above"
select.X = "extend_line_above"
normal."#" = [ "toggle_comments" ]
select."#" = [ "toggle_comments" ]
# hjkl
normal.H = "expand_selection"
select.H = "expand_selection"
normal.L = "shrink_selection"
select.L = "shrink_selection"
normal.J = "select_next_sibling"
select.J = "select_next_sibling"
normal.K = "select_prev_sibling"
select.K = "select_prev_sibling"

normal.A-j = [ "ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection", "add_newline_below", "move_line_down", "replace_with_yanked" ]
select.A-j = [ "ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection", "add_newline_below", "move_line_down", "replace_with_yanked" ]
insert.A-j = [ "ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection", "add_newline_below", "move_line_down", "replace_with_yanked" ]
normal.A-k = [ "ensure_selections_forward", "flip_selections", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection", "move_line_up", "add_newline_above", "move_line_up", "replace_with_yanked" ]
select.A-k = [ "ensure_selections_forward", "flip_selections", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection", "move_line_up", "add_newline_above", "move_line_up", "replace_with_yanked" ]
insert.A-k = [ "ensure_selections_forward", "flip_selections", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection", "move_line_up", "add_newline_above", "move_line_up", "replace_with_yanked" ]
normal.A-J = [ "extend_line_down", "extend_to_line_bounds" ]
select.A-J = [ "extend_line_down", "extend_to_line_bounds" ]
insert.A-J = [ "extend_line_down", "extend_to_line_bounds" ]
normal.A-K = [ "extend_line_up", "extend_to_line_bounds" ]
select.A-K = [ "extend_line_up", "extend_to_line_bounds" ]
insert.A-K = [ "extend_line_up", "extend_to_line_bounds" ]
normal.C-A-j = [ "ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "yank", "add_newline_below", "move_line_down", "replace_with_yanked" ]
select.C-A-j = [ "ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "yank", "add_newline_below", "move_line_down", "replace_with_yanked" ]
insert.C-A-j = [ "ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "yank", "add_newline_below", "move_line_down", "replace_with_yanked" ]
normal.C-A-k = [ "ensure_selections_forward", "flip_selections", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "yank", "add_newline_above", "move_line_up", "replace_with_yanked" ]
select.C-A-k = [ "ensure_selections_forward", "flip_selections", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "yank", "add_newline_above", "move_line_up", "replace_with_yanked" ]
insert.C-A-k = [ "ensure_selections_forward", "flip_selections", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "yank", "add_newline_above", "move_line_up", "replace_with_yanked" ]
normal.A-h = [ "goto_line_start" ]
select.A-h = [ "goto_line_start" ]
insert.A-h = [ "goto_line_start" ]
normal.A-l = [ "goto_line_end" ]
select.A-l = [ "goto_line_end" ]
insert.A-l = [ "goto_line_end" ]
# cmds
normal.C-r = [ ":config-reload", ":reload", ":lsp-restart" ]
select.C-r = [ ":config-reload", ":reload", ":lsp-restart" ]
insert.C-r = [ ":config-reload", ":reload", ":lsp-restart" ]
normal.C-q = [ ":quit" ]
select.C-q = [ ":quit" ]
insert.C-q = [ ":quit" ]
normal.C-s = [ ":w", ":format" ]
select.C-s = [ ":w", ":format" ]
insert.C-s = [ ":w", ":format" ]
# clipboard
normal.C-c = [ ":clipboard-yank" ]
select.C-c = [ ":clipboard-yank" ]
insert.C-c = [ ":clipboard-yank" ]
normal.C-x = [ ":clipboard-yank", "delete_selection_noyank" ]
select.C-x = [ ":clipboard-yank", "delete_selection_noyank" ]
insert.C-x = [ ":clipboard-yank", "delete_selection_noyank" ]
normal.C-v = [ ":clipboard-paste-after", "collapse_selection" ]
select.C-v = [ ":clipboard-paste-replace", "collapse_selection" ]
insert.C-v = [ ":clipboard-paste-after", "collapse_selection" ]
normal.C-V = [ ":clipboard-paste-before", "collapse_selection" ]
select.C-V = [ ":clipboard-paste-replace", "collapse_selection" ]
insert.C-V = [ ":clipboard-paste-before", "collapse_selection" ]
normal.C-z = [ "undo", "collapse_selection" ]
select.C-z = [ "undo", "collapse_selection" ]
insert.C-z = [ "undo", "collapse_selection" ]
normal.C-Z = [ "redo" ]
select.C-Z = [ "redo" ]
insert.C-Z = [ "redo" ]
# no alt
normal.A-up = "no_op"
select.A-up = "no_op"
insert.A-up = "no_op"
normal.A-down = "no_op"
select.A-down = "no_op"
insert.A-down = "no_op"
normal.A-left = "no_op"
select.A-left = "no_op"
insert.A-left = "no_op"
normal.A-right = "no_op"
select.A-right = "no_op"
insert.A-right = "no_op"
normal.A-S-down = "no_op"
select.A-S-down = "no_op"
insert.A-S-down = "no_op"
